module.exports =
  'slim':         require './slim'
  'coffee':       require './coffee'
  'sass':         require './sass'
  'cmq':          require './cmq'
  'autoprefixer': require './autoprefixer'
  'csscomb':      require './csscomb'
  'connect':      require './connect'
  'watch':        require './watch'
  'imagemin':     require './imagemin'
  'cssmin':       require './cssmin'
  'browser_sync': require './browser_sync'
  'bower':        require './bower'
  'prettify':     require './prettify'
  'htmlmin':      require './htmlmin'
  # 'csscss':       require './csscss'
  # 'csslint':      require './csslint'
